---
- name: Create projects directory
  file: path=~/src state=directory

- name: Update homebrew
  homebrew:
    update_homebrew=yes

- name: Install packages
  homebrew:
    name: [git,wget,zsh,the_silver_searcher,postgresql,node,fzf, rbenv, rbenv-vars, rbenv-aliases]
    state: present


- name: Install Casks
  homebrew_cask:
    name: [pgadmin4, keepingyouawake, spectacle, slack, libreoffice, gimp, filezilla, vlc, transmission]
    state: present

- name: Install rubies
  command: rbenv install 2.5.1
